# @package _global_
# DO NOT REMOVE THE LINE ABOVE

# general
sdt: 25-05-22 00:00
edt: 25-05-22 23:59
antennaids: ["ACM0"]
hgts: [0.2]
lla: [-44.71660967, 169.17844583, 342.4]

# snr2arcs parameters
azilims: [0, 360]  # 190, 250
elvlims: [3, 35]  # 5, 20
rhlims: [1, 6]

# arc2splines parameters
kdt: 7200
fixed_std: 1
